export const colors = {
  backgrounds: {
    card: 'bg-card',
    sidebar: 'bg-sidebar',
    sidebarPrimary: 'bg-sidebar-primary',
    sidebarAccent: 'bg-sidebar-accent',
    background: 'bg-background',
    backgroundMuted: 'bg-muted',
    backgroundGray: 'bg-background-gray',
    primary: 'bg-primary',
    primaryMuted: 'bg-primary-muted',
    secondary: 'bg-secondary',
    accent: 'bg-accent',
    destructive: 'bg-destructive',
    destructiveMuted: 'bg-destructive-muted',
    warning: 'bg-warning',
    warningMuted: 'bg-warning-muted',
    success: 'bg-success',
    successMuted: 'bg-success-muted',
  },
  textColors: {
    white: 'text-white',
    sidebar: 'text-sidebar-foreground',
    sidebarPrimary: 'text-sidebar-primary-foreground',
    sidebarAccent: 'text-sidebar-accent-foreground',
    foreground: 'text-foreground',
    background: 'text-background',
    foregroundMuted: 'text-muted-foreground',
    input: 'text-input',
    primary: 'text-primary-foreground',
    primaryMuted: 'text-primary-foreground-muted',
    secondary: 'text-secondary-foreground',
    accent: 'text-accent-foreground',
    destructive: 'text-destructive-foreground',
    destructiveMuted: 'text-destructive-foreground-muted',
    warning: 'text-warning-foreground',
    warningMuted: 'text-warning-foreground-muted',
    success: 'text-success-foreground',
    successMuted: 'text-success-foreground-muted',
  },
  darkTextColors: {
    sidebar: 'dark:text-sidebar-foreground',
    sidebarPrimary: 'dark:text-sidebar-primary-foreground',
    sidebarAccent: 'dark:text-sidebar-accent-foreground',
    foreground: 'dark:text-foreground',
    background: 'dark:text-background',
    foregroundMuted: 'dark:text-foreground-muted',
    input: 'dark:text-input',
    primary: 'dark:text-primary-foreground',
    primaryMuted: 'dark:text-primary-foreground-muted',
    secondary: 'dark:text-secondary-foreground',
    accent: 'dark:text-accent-foreground',
    destructive: 'dark:text-destructive-foreground',
    warning: 'dark:text-warning-foreground',
    warningMuted: 'dark:text-warning-foreground-muted',
    success: 'dark:text-success-foreground',
    successMuted: 'dark:text-success-foreground-muted',
  },
  borderColors: {
    border: 'border-border',
    primary: 'border-primary',
    foreground: 'border-foreground',
    input: 'border-input',
    destructive: 'border-destructive-border',
    warning: 'border-warning-border',
    sidebar: 'border-sidebar',
  },
  ringColors: {
    ring: 'ring-ring',
    sidebar: 'ring-sidebar',
  },
}

export type TextColor = keyof typeof colors.textColors
export type DarkTextColor = keyof typeof colors.darkTextColors
export type BackgroundColor = keyof typeof colors.backgrounds
export type RingColor = keyof typeof colors.ringColors
export type BorderColor = keyof typeof colors.borderColors
